project:
  type: website
  output-dir: docs
website:
  title: "Hemanta Panthi"
  navbar:
    right:
      - home.qmd
      - icon: github
        href: https://github.com/heymant1
      - icon: twitter
        href: https://twitter.com
      - About.qmd
      


format:
  html:
    theme: yeti
    css: styles.css

editor: visual

